baseURL = "http://example.org/"
languageCode = "fr-fr"
title = "974 Attitude"
theme = "974attitude"
staticman_api = "https://comments-static.herokuapp.com/v2/entry/zourite/974attitude/master/comments"