[build]
  
  [[redirects]]
    from = "/2009/12/alain-peters/"
    to = "/alain-peters/"
    status = 301
    force = true

  [[redirects]]
    from = "/974/culture/"
    to = "/categories/culture/"
    status = 301
    force = true